/**
 * VrmCastPanel.tsx — main UI for the VRM Cast plugin.
 *
 * Scans public/models/ for .vrm files and public/vrma/ for .vrma files.
 * Lets you build a cast (actors + timeline) and exports scenes/cast.json
 * in the PlayController SceneScript format.
 */

import React, { useState, useEffect, CSSProperties } from "react";
import { Editor } from "babylonjs-editor";
import { dirname, join, basename } from "path";
import { readdir, outputJSON, pathExists, ensureDir } from "fs-extra";

// ── Types ──────────────────────────────────────────────────────────────────

interface ActorEntry {
  id: string;
  vrm: string;
  x: number;
  y: number;
  z: number;
  rotY: number;
  initialClip: string;
  loop: boolean;
}

interface EventEntry {
  start: number;
  actor: string;
  action: "animate" | "stop";
  clip: string;
  loop: boolean;
}

interface Props {
  editor: Editor;
}

// ── Component ──────────────────────────────────────────────────────────────

export function VrmCastPanel({ editor }: Props) {
  const [vrmFiles, setVrmFiles]   = useState<string[]>([]);
  const [vrmaFiles, setVrmaFiles] = useState<string[]>([]);
  const [actors, setActors]       = useState<ActorEntry[]>([]);
  const [events, setEvents]       = useState<EventEntry[]>([]);
  const [status, setStatus]       = useState<{ msg: string; ok: boolean } | null>(null);

  useEffect(() => { scanFiles(); }, []);

  // ── File scanning ──────────────────────────────────────────────────────

  async function scanFiles() {
    if (!editor.state.projectPath) return;
    const pub = join(dirname(editor.state.projectPath), "public");

    const vrms: string[]  = [];
    const vrmas: string[] = [];

    try {
      const modelsDir = join(pub, "models");
      if (await pathExists(modelsDir)) {
        const files = await readdir(modelsDir);
        vrms.push(...files.filter(f => f.toLowerCase().endsWith(".vrm")).map(f => `models/${f}`));
      }
    } catch { /* models folder absent */ }

    try {
      const vrmaDir = join(pub, "vrma");
      if (await pathExists(vrmaDir)) {
        const files = await readdir(vrmaDir);
        vrmas.push(...files.filter(f => f.toLowerCase().endsWith(".vrma")).map(f => `vrma/${f}`));
      }
    } catch { /* vrma folder absent */ }

    setVrmFiles(vrms);
    setVrmaFiles(vrmas);
  }

  // ── Actor CRUD ─────────────────────────────────────────────────────────

  function addActor() {
    const id = `actor${actors.length + 1}`;
    setActors(prev => [...prev, {
      id,
      vrm:         vrmFiles[0] ?? "",
      x:           prev.length * 1.5,
      y:           0,
      z:           0,
      rotY:        0,
      initialClip: vrmaFiles[0] ?? "",
      loop:        true,
    }]);
  }

  function removeActor(i: number) {
    setActors(prev => prev.filter((_, idx) => idx !== i));
  }

  function patchActor(i: number, patch: Partial<ActorEntry>) {
    setActors(prev => prev.map((a, idx) => idx === i ? { ...a, ...patch } : a));
  }

  // ── Event CRUD ─────────────────────────────────────────────────────────

  function addEvent() {
    setEvents(prev => [...prev, {
      start:  5,
      actor:  actors[0]?.id ?? "",
      action: "animate",
      clip:   vrmaFiles[0] ?? "",
      loop:   true,
    }]);
  }

  function removeEvent(i: number) {
    setEvents(prev => prev.filter((_, idx) => idx !== i));
  }

  function patchEvent(i: number, patch: Partial<EventEntry>) {
    setEvents(prev => prev.map((e, idx) => idx === i ? { ...e, ...patch } : e));
  }

  // ── Export ─────────────────────────────────────────────────────────────

  async function exportCast() {
    if (!editor.state.projectPath) return;
    const pub     = join(dirname(editor.state.projectPath), "public");
    const outPath = join(pub, "scenes", "cast.json");

    const t0events = actors
      .filter(a => a.initialClip)
      .map(a => ({ start: 0, actor: a.id, action: "animate" as const, clip: a.initialClip, loop: a.loop }));

    const laterEvents = events.map(e => ({
      start:  e.start,
      actor:  e.actor,
      action: e.action,
      ...(e.action === "animate" ? { clip: e.clip, loop: e.loop } : {}),
    }));

    const script = {
      metadata: { title: "VRM Cast", description: "Generated by VRM Cast Plugin" },
      actors: actors.map(a => ({
        id:            a.id,
        vrm:           a.vrm,
        startPosition: { x: a.x, y: a.y, z: a.z },
        startRotation: { y: a.rotY },
      })),
      timeline: [...t0events, ...laterEvents].sort((a, b) => a.start - b.start),
    };

    try {
      await ensureDir(join(pub, "scenes"));
      await outputJSON(outPath, script, { spaces: 2 });
      const msg = `Saved public/scenes/cast.json (${actors.length} actors, ${script.timeline.length} events)`;
      setStatus({ msg, ok: true });
      editor.layout.console.log(`[VRM Cast] ${msg}`);
    } catch (err: any) {
      const msg = `Export failed: ${err?.message ?? err}`;
      setStatus({ msg, ok: false });
      editor.layout.console.error(`[VRM Cast] ${msg}`);
    }
  }

  // ── Styles ─────────────────────────────────────────────────────────────

  const S: Record<string, CSSProperties> = {
    panel: {
      padding: "12px", fontFamily: "monospace", fontSize: "12px",
      color: "#ccc", overflowY: "auto", height: "100%",
      boxSizing: "border-box", background: "#1e1e1e",
    },
    header: {
      display: "flex", justifyContent: "space-between",
      alignItems: "center", marginBottom: "14px",
    },
    title: { color: "#fff", fontWeight: "bold", fontSize: "13px" },
    sectionHeader: {
      display: "flex", justifyContent: "space-between",
      alignItems: "center", marginBottom: "6px",
    },
    heading: {
      color: "#aaa", fontSize: "10px",
      textTransform: "uppercase", letterSpacing: "1px",
    },
    card: {
      background: "#252525", borderRadius: "4px",
      padding: "8px", marginBottom: "6px",
    },
    row: { display: "flex", gap: "6px", alignItems: "center", marginBottom: "4px", flexWrap: "wrap" },
    label: { color: "#666", fontSize: "11px" },
    input: {
      background: "#333", border: "1px solid #555", color: "#eee",
      padding: "2px 6px", borderRadius: "3px", fontSize: "12px",
    },
    numInput: {
      background: "#333", border: "1px solid #555", color: "#eee",
      padding: "2px 4px", borderRadius: "3px", fontSize: "12px", width: "54px",
    },
    select: {
      background: "#333", border: "1px solid #555", color: "#eee",
      padding: "2px 4px", borderRadius: "3px", fontSize: "12px", maxWidth: "170px",
    },
    btn: {
      background: "#3a3a3a", border: "1px solid #555", color: "#ddd",
      padding: "3px 10px", borderRadius: "3px", cursor: "pointer", fontSize: "12px",
    },
    btnPrimary: {
      background: "#005fa3", border: "1px solid #0080d0", color: "#fff",
      padding: "3px 12px", borderRadius: "3px", cursor: "pointer", fontSize: "12px",
      fontWeight: "bold",
    },
    btnDanger: {
      background: "transparent", border: "1px solid #633", color: "#f66",
      padding: "2px 7px", borderRadius: "3px", cursor: "pointer", fontSize: "12px",
    },
    footer: {
      color: "#444", fontSize: "11px",
      borderTop: "1px solid #2a2a2a", paddingTop: "8px", marginTop: "14px",
    },
  };

  // ── Render ─────────────────────────────────────────────────────────────

  return (
    <div style={S.panel}>

      {/* Header */}
      <div style={S.header}>
        <span style={S.title}>VRM Cast</span>
        <div style={{ display: "flex", gap: "6px" }}>
          <button style={S.btn} onClick={scanFiles} title="Re-scan public/ for VRM and VRMA files">↺ Scan</button>
          <button style={S.btnPrimary} onClick={exportCast} disabled={actors.length === 0}>
            Export cast.json
          </button>
        </div>
      </div>

      {/* ── Actors ── */}
      <div style={{ marginBottom: "16px" }}>
        <div style={S.sectionHeader}>
          <span style={S.heading}>Actors</span>
          <button style={S.btn} onClick={addActor} disabled={vrmFiles.length === 0}>+ Add Actor</button>
        </div>

        {vrmFiles.length === 0 && (
          <div style={{ color: "#555", fontSize: "11px", marginBottom: "4px" }}>
            No .vrm files found in public/models/ — click ↺ Scan after copying models.
          </div>
        )}

        {actors.map((actor, i) => (
          <div key={i} style={S.card}>
            {/* id + vrm + remove */}
            <div style={S.row}>
              <input
                style={{ ...S.input, width: "72px" }}
                value={actor.id}
                onChange={e => patchActor(i, { id: e.target.value })}
                placeholder="id"
                title="Unique actor id used in timeline events"
              />
              <select
                style={S.select}
                value={actor.vrm}
                onChange={e => patchActor(i, { vrm: e.target.value })}
                title="VRM model file"
              >
                {vrmFiles.map(f => <option key={f} value={f}>{basename(f)}</option>)}
              </select>
              <button style={S.btnDanger} onClick={() => removeActor(i)} title="Remove actor">×</button>
            </div>

            {/* position + rotation */}
            <div style={S.row}>
              <span style={S.label}>pos</span>
              {(["x", "y", "z"] as const).map(axis => (
                <input
                  key={axis}
                  style={S.numInput}
                  type="number"
                  step="0.1"
                  value={actor[axis]}
                  onChange={e => patchActor(i, { [axis]: parseFloat(e.target.value) || 0 })}
                  placeholder={axis}
                  title={`World ${axis} position`}
                />
              ))}
              <span style={S.label}>rotY°</span>
              <input
                style={S.numInput}
                type="number"
                step="5"
                value={actor.rotY}
                onChange={e => patchActor(i, { rotY: parseFloat(e.target.value) || 0 })}
                title="Y rotation in degrees"
              />
            </div>

            {/* initial clip */}
            <div style={S.row}>
              <span style={S.label}>clip at t=0</span>
              <select
                style={S.select}
                value={actor.initialClip}
                onChange={e => patchActor(i, { initialClip: e.target.value })}
                title="VRMA clip to play immediately"
              >
                <option value="">— none —</option>
                {vrmaFiles.map(f => <option key={f} value={f}>{basename(f)}</option>)}
              </select>
              <label style={{ ...S.label, display: "flex", alignItems: "center", gap: "4px", cursor: "pointer" }}>
                <input
                  type="checkbox"
                  checked={actor.loop}
                  onChange={e => patchActor(i, { loop: e.target.checked })}
                />
                loop
              </label>
            </div>
          </div>
        ))}
      </div>

      {/* ── Timeline Events ── */}
      <div style={{ marginBottom: "16px" }}>
        <div style={S.sectionHeader}>
          <span style={S.heading}>Timeline Events</span>
          <button style={S.btn} onClick={addEvent} disabled={actors.length === 0}>+ Add Event</button>
        </div>
        <div style={{ color: "#555", fontSize: "11px", marginBottom: "6px" }}>
          Additional clip changes after t=0. Actor initial clips are always added automatically.
        </div>

        {events.map((ev, i) => (
          <div key={i} style={{ ...S.card, ...S.row }}>
            <span style={S.label}>t=</span>
            <input
              style={{ ...S.numInput, width: "50px" }}
              type="number"
              step="0.5"
              min="0"
              value={ev.start}
              onChange={e => patchEvent(i, { start: parseFloat(e.target.value) || 0 })}
              title="Time in seconds"
            />
            <select
              style={{ ...S.select, width: "80px" }}
              value={ev.actor}
              onChange={e => patchEvent(i, { actor: e.target.value })}
            >
              {actors.map(a => <option key={a.id} value={a.id}>{a.id}</option>)}
            </select>
            <select
              style={{ ...S.select, width: "72px" }}
              value={ev.action}
              onChange={e => patchEvent(i, { action: e.target.value as "animate" | "stop" })}
            >
              <option value="animate">animate</option>
              <option value="stop">stop</option>
            </select>
            {ev.action === "animate" && (
              <>
                <select
                  style={S.select}
                  value={ev.clip}
                  onChange={e => patchEvent(i, { clip: e.target.value })}
                >
                  {vrmaFiles.map(f => <option key={f} value={f}>{basename(f)}</option>)}
                </select>
                <label style={{ ...S.label, display: "flex", alignItems: "center", gap: "4px", cursor: "pointer" }}>
                  <input
                    type="checkbox"
                    checked={ev.loop}
                    onChange={e => patchEvent(i, { loop: e.target.checked })}
                  />
                  loop
                </label>
              </>
            )}
            <button style={S.btnDanger} onClick={() => removeEvent(i)} title="Remove event">×</button>
          </div>
        ))}
      </div>

      {/* Status message */}
      {status && (
        <div style={{ color: status.ok ? "#4c9" : "#f66", fontSize: "11px", marginBottom: "8px" }}>
          {status.ok ? "✓ " : "✗ "}{status.msg}
        </div>
      )}

      {/* Footer */}
      <div style={S.footer}>
        {vrmFiles.length} VRM · {vrmaFiles.length} VRMA · {actors.length} actors · {events.length} events
      </div>

    </div>
  );
}
