
/**
 * Generated by Babylon.js Editor
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_box from "./scripts/box";
import * as scripts_vrm_char from "./scripts/VrmCharacter";
import * as scripts_vrm_anim from "./scripts/VrmAnimation";
import * as scripts_vrm_face from "./scripts/VrmFace";

export const scriptsMap = {
    "scripts/box.ts": scripts_box,
    "scripts/VrmCharacter.ts": scripts_vrm_char,
    "scripts/VrmAnimation.ts": scripts_vrm_anim,
    "scripts/VrmFace.ts": scripts_vrm_face
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
